# ${THEME_HEADER}
[urgency_low]
background = "${BG}"
foreground = "${FG}"
frame_color = "${BLACK}"

[urgency_normal]
background = "${BG}"
foreground = "${FG}"
frame_color = "${ACCENT}"

[urgency_critical]
background = "${BG}"
foreground = "${RED}"
frame_color = "${RED}"
