#!/bin/bash

# Notify that picom is starting
notify-send "Picom" "Starting picom..."

# Start picom in the background
picom &

# Store the PID to kill it later
PICOM_PID=$!

# Wait 5 seconds
sleep 5

# Kill picom
kill $PICOM_PID 2>/dev/null

# Notify that picom has been killed
notify-send "Picom" "Picom killed after 5 seconds."
