#!/usr/bin/env bash

# Define the brightness increment/decrement value
BRIGHTNESS_STEP=10

# Get the current brightness level
CURRENT_BRIGHTNESS=$(ddcutil getvcp 10 | awk '{print $9}' | tr -d ,)

case "$1" in
  "up")
    # Increase brightness by $BRIGHTNESS_STEP
    ddcutil setvcp 10 + $BRIGHTNESS_STEP
    NEW_BRIGHTNESS=$(ddcutil getvcp 10 | awk '{print $9}'| tr -d ,)
    notify-send "Brightness" "Increased to ${NEW_BRIGHTNESS}%"
    ;;
  "down")
    # Decrease brightness by $BRIGHTNESS_STEP
    ddcutil setvcp 10 - $BRIGHTNESS_STEP
    NEW_BRIGHTNESS=$(ddcutil getvcp 10 | awk '{print $9}'| tr -d ,)
    notify-send "Brightness" "Decreased to ${NEW_BRIGHTNESS}%"
    ;;
  *)
    echo "Usage: $0 <up|down>"
    exit 1
    ;;
esac
