# Disable mouse acceleration
Section "InputClass"
	Identifier "libinput pointer flat profile"
	MatchIsPointer "on"
	MatchDevicePath "/dev/input/event*"
	Driver "libinput"
	Option "AccelProfile" "flat"
EndSection
