# Oxocarbon
BG=#161616
BG_ALT=#262626
FG=#f2f4f8
FG_DIM=#6f6f6f
ACCENT=#be95ff
SELECTION=#393939
BLACK=#525252
RED=#ee5396
GREEN=#42be65
YELLOW=#ffe97b
BLUE=#78a9ff
MAGENTA=#be95ff
CYAN=#3ddbd9
WHITE=#dde1e6
ORANGE=#ff7eb6
