# Rose Pine
BG=#191724
BG_ALT=#26233a
FG=#e0def4
FG_DIM=#716d88
ACCENT=#ebbcba
SELECTION=#403d52
BLACK=#524f67
RED=#eb6f92
GREEN=#9ccfd8
YELLOW=#f6c177
BLUE=#528aa1
MAGENTA=#c4a7e7
CYAN=#9ccfd8
WHITE=#908caa
ORANGE=#ea9a97
